#
# Copyright Â© 2018 Apple Inc. and the ServiceTalk project authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"

services:

  java:
    image: java:latest
    build:
      context: .
      dockerfile: Dockerfile

  redis-2:
    image: redis:2
    networks: [test-net]
    command: bash -c "redis-server --port 6379 & redis-server --port 6378 --requirepass password"

  redis-3:
    image: redis:3
    networks: [test-net]
    command: bash -c "redis-server --port 6379 & redis-server --port 6378 --requirepass password"

  redis-4:
    image: redis:4
    networks: [test-net]
    command: bash -c "redis-server --port 6379 & redis-server --port 6378 --requirepass password"

  test:
    depends_on: [java]
    image: java:latest
    environment:
      - CI=true
    command: /bin/bash -cl "./gradlew clean build"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gradle${EXECUTOR_NUMBER}:/root/.gradle
      - ..:/code
    working_dir: /code
    networks: [test-net]

  test-redis-2:
    depends_on: [java, redis-2]
    image: java:latest
    environment:
      - CI=true
    command: /bin/bash -cl "REDIS_HOST=redis-3 REDIS_PORT=6379 REDIS_AUTH_PORT=6378 ./gradlew clean test"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gradle${EXECUTOR_NUMBER}:/root/.gradle
      - ..:/code
    working_dir: /code
    networks: [test-net]

  test-redis-3:
    depends_on: [java, redis-3]
    image: java:latest
    environment:
      - CI=true
    command: /bin/bash -cl "REDIS_HOST=redis-3 REDIS_PORT=6379 REDIS_AUTH_PORT=6378 ./gradlew clean test"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gradle${EXECUTOR_NUMBER}:/root/.gradle
      - ..:/code
    working_dir: /code
    networks: [test-net]

  test-redis-4:
    depends_on: [java, redis-4]
    image: java:latest
    environment:
      - CI=true
    command: /bin/bash -cl "REDIS_HOST=redis-4 REDIS_PORT=6379 REDIS_AUTH_PORT=6378 ./gradlew clean test"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gradle${EXECUTOR_NUMBER}:/root/.gradle
      - ..:/code
    working_dir: /code
    networks: [test-net]

  publish-snapshot:
    depends_on: [java]
    image: java:latest
    environment:
      - CI=true
    command: /bin/bash -cl "BINTRAY_USER=$BINTRAY_USER BINTRAY_KEY=$BINTRAY_KEY ./gradlew clean test bintrayUpload"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gradle${EXECUTOR_NUMBER}:/root/.gradle
      - ..:/code
    working_dir: /code

  publish-release:
    depends_on: [java]
    image: java:latest
    environment:
      - CI=true
    command: /bin/bash -cl "BINTRAY_USER=$BINTRAY_USER BINTRAY_KEY=$BINTRAY_KEY ./gradlew clean test bintrayUpload -PreleaseBuild=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gradle${EXECUTOR_NUMBER}:/root/.gradle
      - ..:/code
    working_dir: /code

networks:
  test-net:
